src/AppBundle/Entity/Comment.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use UserBundle\Entity\User;
/**
 * Comment
 *
 * @ORM\Table(name="comment_table")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var bool
     *
     * @ORM\Column(name="enabled", type="boolean")
     */
    private $enabled;


    /**
     * @ORM\ManyToOne(targetEntity="Poster", inversedBy="comments")
     * @ORM\JoinColumn(name="poster_id", referencedColumnName="id", nullable=true)
     */
    private $poster;


    /**
     * @ORM\ManyToOne(targetEntity="Channel", inversedBy="comments")
     * @ORM\JoinColumn(name="channel_id", referencedColumnName="id", nullable=true)
     */
    private $channel;


    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="comments")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    private $user;
    public function __construct()
    {
        $this->created= new \DateTime();

    }
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }



    /**
     * Set content
     *
     * @param string $content
     * @return Comment
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }
    public function getContentclear()
    {
        return base64_decode($this->content);
    }
    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Comment
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set enabled
     *
     * @param boolean $enabled
     * @return Comment
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }
    /**
    * Get user
    * @return  
    */
    public function getUser()
    {
        return $this->user;
    }
    
    /**
    * Set user
    * @return $this
    */
    public function setUser(User $user)
    {
        $this->user = $user;
        return $this;
    }
    /**
     * Get enabled
     *
     * @return boolean 
     */
    public function getEnabled()
    {
        return $this->enabled;
    }


  	/**
  	* Get poster
  	* @return  
  	*/
  	public function getPoster()
  	{
  	    return $this->poster;
  	}
  	
  	/**
  	* Set poster
  	* @return $this
  	*/
  	public function setPoster($poster)
  	{
  	    $this->poster = $poster;
  	    return $this;
  	}
    /**
    * Get channel
    * @return  
    */
    public function getChannel()
    {
        return $this->channel;
    }
    
    /**
    * Set channel
    * @return $this
    */
    public function setChannel($channel)
    {
        $this->channel = $channel;
        return $this;
    }
  
}

src/AppBundle/Form/MovieType.php
<?php
namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class MovieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title');
        $builder->add('label');
        $builder->add('sublabel');
        $builder->add('description');
        $builder->add('year');
        $builder->add('enabled');
        $builder->add('comment');
        $builder->add('imdb');
        $builder->add('classification');
        $builder->add('playas' ,ChoiceType::class, array(
                'choices' => array(
                    "Free"=> 1 ,
                    "Premuim"=> 2,
                    "Unlock with rewards Ads"=> 3
                )));   
        $builder->add('downloadas' ,ChoiceType::class, array(
                'choices' => array(
                    "Free"=> 1 ,
                    "Premuim"=> 2,
                    "Unlock with rewards Ads"=> 3
                )));  
        $builder->add('duration');
        $builder->add('tags');
        $builder->add('sourcetype' ,ChoiceType::class, array(
                'choices' => array(
                    "Youtube Url"  =>       1,
                    "m3u8 Url"     =>       2,
                    "MOV Url"      =>       3,
                    "MP4 Url"      =>       4,
                    "MKV Url"      =>       6,
                    "WEBM Url"     =>       7,
                    "Embed source" =>       8,
                    "File (MP4/MOV/MKV/WEBM)" =>5
                )));
        $builder->add('sourceurl');
        $builder->add("sourcefile",null,array("label"=>"","required"=>false));
        $builder->add('trailerurl');
        $builder->add("genres",EntityType::class,
                  array(
                        'class' => 'AppBundle:Genre',
                        'expanded' => true,
                        "multiple" => "true",
                        'by_reference' => false
                      )
                  );
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $article = $event->getData();
            $form = $event->getForm();
            if ($article and null !== $article->getId()) {
                 $form->add("fileposter",null,array("label"=>"","required"=>false));
                 $form->add("filecover",null,array("label"=>"","required"=>false));
            }else{
                 $form->add("fileposter",null,array("label"=>"","required"=>false));
                 $form->add("filecover",null,array("label"=>"","required"=>false));
            }
        });
        $builder->add('save', SubmitType::class,array("label"=>"SAVE"));

    }
    public function getName()
    {
        return 'movie';
    }
}
?>

src/AppBundle/Controller/MovieController.php
<?php 
namespace AppBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use AppBundle\Entity\Poster;
use AppBundle\Entity\Genre;
use AppBundle\Entity\Rate;
use AppBundle\Entity\Role;
use AppBundle\Entity\Actor;

use AppBundle\Entity\Source;
use AppBundle\Entity\Subtitle;
use MediaBundle\Entity\Media;
use AppBundle\Form\MovieType;
use AppBundle\Form\TrailerType;

use AppBundle\Form\SubtitleType;
use AppBundle\Form\RoleType;
use AppBundle\Form\SourceType;
use AppBundle\Form\EditMovieType;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;



class MovieController extends Controller

{
    public function api_by_idAction(Request $request,$id)
    {
        $em=$this->getDoctrine()->getManager();
        $poster=$em->getRepository("AppBundle:Poster")->find($id);
        if ($poster==null) {
            throw new NotFoundHttpException("Page not found");
        }
        return $this->render('AppBundle:Movie:api_one.html.php', array("poster" => $poster));
    }
    public function api_add_viewAction(Request $request, $token) {
        if ($token != $this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");
        }
        $em = $this->getDoctrine()->getManager();
        $id = $request->get("id");
        $poster = $em->getRepository("AppBundle:Poster")->findOneBy(array("id"=>$id,"enabled"=>true));
        if ($poster == null) {
            throw new NotFoundHttpException("Page not found");
        }
        $poster->setViews($poster->getViews() + 1);
        $em->flush();
        $encoders = array(new XmlEncoder(), new JsonEncoder());
        $normalizers = array(new ObjectNormalizer());
        $serializer = new Serializer($normalizers, $encoders);
        $jsonContent = $serializer->serialize($poster->getViews(), 'json');
        return new Response($jsonContent);
    }
    public function api_add_shareAction(Request $request, $token) {
        if ($token != $this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");
        }
        $em = $this->getDoctrine()->getManager();
        $id = $request->get("id");
        $poster = $em->getRepository("AppBundle:Poster")->findOneBy(array("id"=>$id,"enabled"=>true));
        if ($poster == null) {
            throw new NotFoundHttpException("Page not found");
        }
        $poster->setShares($poster->getShares() + 1);
        $em->flush();
        $encoders = array(new XmlEncoder(), new JsonEncoder());
        $normalizers = array(new ObjectNormalizer());
        $serializer = new Serializer($normalizers, $encoders);
        $jsonContent = $serializer->serialize($poster->getShares(), 'json');
        return new Response($jsonContent);
    }
    public function api_add_downloadAction(Request $request, $token) {
        if ($token != $this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");
        }
        $em = $this->getDoctrine()->getManager();
        $id = $request->get("id");
        $poster = $em->getRepository("AppBundle:Poster")->findOneBy(array("id"=>$id,"enabled"=>true));
        if ($poster == null) {
            throw new NotFoundHttpException("Page not found");
        }
        $poster->setDownloads($poster->getDownloads() + 1);
        $em->flush();
        $encoders = array(new XmlEncoder(), new JsonEncoder());
        $normalizers = array(new ObjectNormalizer());
        $serializer = new Serializer($normalizers, $encoders);
        $jsonContent = $serializer->serialize($poster->getDownloads(), 'json');
        return new Response($jsonContent);
    }
    public function api_poster_by_filtresAction(Request $request, $genre,$order,$page, $token) {
        if ($token != $this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");
        }
        $nombre = 30;
        $em = $this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Poster');
        $dir = "DESC";
        if("title"==$order){
            $dir="ASC";
        }
        if($genre==0){
            $query = $repository->createQueryBuilder('p')
                ->where("p.enabled = true")
                ->addOrderBy('p.'.$order, $dir)
                ->addOrderBy('p.id', 'ASC')
                ->setFirstResult($nombre * $page)
                ->setMaxResults($nombre)
                ->getQuery();         
        }else{
            $query = $repository->createQueryBuilder('p')
                ->leftJoin('p.genres', 'g')
                ->where("p.enabled = true",'g.id = ' . $genre)
                ->addOrderBy('p.'.$order, $dir)
                ->addOrderBy('p.id', 'ASC')
                ->setFirstResult($nombre * $page)
                ->setMaxResults($nombre)
                ->getQuery();         
        }  
        $posters_list = $query->getResult();
        return $this->render('AppBundle:Movie:api_all.html.php', array("posters_list" => $posters_list));
    }
    public function api_by_filtresAction(Request $request, $genre,$order,$page, $token) {
        if ($token != $this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");
        }
        $nombre = 30;
        $em = $this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Poster');
        $dir = "DESC";
        if("title"==$order){
            $dir="ASC";
        }
        if($genre==0){
            $query = $repository->createQueryBuilder('p')
                ->where("p.enabled = true","p.type like 'movie' ")
                ->addOrderBy('p.'.$order, $dir)
                ->addOrderBy('p.id', 'ASC')
                ->setFirstResult($nombre * $page)
                ->setMaxResults($nombre)
                ->getQuery();
            }else{
                 $query = $repository->createQueryBuilder('p')
                ->leftJoin('p.genres', 'g')
                ->where("p.enabled = true","p.type like 'movie' ",'g.id = ' . $genre)
                ->addOrderBy('p.'.$order, $dir)
                ->addOrderBy('p.id', 'ASC')
                ->setFirstResult($nombre * $page)
                ->setMaxResults($nombre)
                ->getQuery();         
            }
        $posters_list = $query->getResult();
        return $this->render('AppBundle:Movie:api_all.html.php', array("posters_list" => $posters_list));
    }
    public function api_randomAction(Request $request, $genres, $token) {
        if ($token != $this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");
        }
        $nombre = 30;
        $em = $this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Poster');
        $query = $repository->createQueryBuilder('p')
            ->leftJoin('p.genres', 'g')
            ->where("p.enabled = true","p.type like 'movie' ",'g.id in (' . $genres . ')')
            ->addSelect('RAND() as HIDDEN rand')
            ->orderBy('rand')
            ->setMaxResults($nombre)
            ->getQuery();
        $posters_list = $query->getResult();
        return $this->render('AppBundle:Movie:api_all.html.php', array("posters_list" => $posters_list));
    }

    public function api_by_actorAction(Request $request, $id, $token) {
        if ($token != $this->container->getParameter('token_app')) {
            throw new NotFoundHttpException("Page not found");
        }
        $nombre = 30;
        $em = $this->getDoctrine()->getManager();
        $imagineCacheManager = $this->get('liip_imagine.cache.manager');
        $repository = $em->getRepository('AppBundle:Poster');
        $query = $repository->createQueryBuilder('p')
            ->leftJoin('p.roles', 'r')
            ->leftJoin('r.actor', 'u')
            ->where("p.enabled = true","u.id  = ".$id)
            ->addOrderBy('p.created', 'DESC')
            ->addOrderBy('p.id', 'ASC')
            ->setMaxResults($nombre)
            ->getQuery();
        $posters_list = $query->getResult();
        return $this->render('AppBundle:Movie:api_all.html.php', array("posters_list" => $posters_list));
    }
    
    public function indexAction(Request $request) {

        $em = $this->getDoctrine()->getManager();
        $q = " ";
        if ($request->query->has("q") and $request->query->get("q") != "") {
            $q .= " AND  p.title like '%" . $request->query->get("q") . "%'";
        }

        $dql = "SELECT p FROM AppBundle:Poster p  WHERE  p.type  like 'movie' " . $q . " ORDER BY p.created desc ";
        $query = $em->createQuery($dql);
        $paginator = $this->get('knp_paginator');
        $movies = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            16
        );
        $movies_count = $em->getRepository('AppBundle:Poster')->countMovies();
        return $this->render('AppBundle:Movie:index.html.twig', array("movies_count" => $movies_count, "movies" => $movies));
    }
    function get_image_mime_type($image_path)
    {
        $mimes  = array(
            IMAGETYPE_GIF => "image/gif",
            IMAGETYPE_JPEG => "image/jpg",
            IMAGETYPE_PNG => "image/png",

src/AppBundle/Resources/views/Movie/cast.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card card-stats card-initial" style="margin: 15px 0;">
					<div class="card-content views-body  pull-right">
						<a href="#" class="btn btn-tab-movie"><i class="material-icons">remove_red_eye</i> {{movie.viewsnumber}} Views</a>
						<a href="#" class="btn btn-tab-movie pull-right"><i class="material-icons">share</i> {{movie.sharesnumber}} Shares</a>
						<a href="#" class="btn btn-tab-movie pull-right"><i class="material-icons">cloud_download</i> {{movie.downloadsnumber}} Downloads</a>
					</div>
					<div class="card-header " data-background-color="green">
						<i class="material-icons">movie_filter</i>
					</div>
					<div class="card-content trailer-body">
						<h4 class="title">Cast : {{movie.title }} </b></h4>
					</div>
                  <div class="tab-moivie">
                    <a href="{{path("app_movie_edit",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">edit</i> Edit</a><a href="{{path("app_movie_sources",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">folder</i> Sources</a><a href="{{path("app_movie_cast",{"id":movie.id})}}" class="btn btn-tab-movie-active"><i class="material-icons">recent_actors</i> Cast</a><a href="{{path("app_movie_trailer",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">movie_filter</i> Trailer</a><a href="{{path("app_movie_subtitles",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">subtitles</i> Subtitles</a><a href="{{path("app_movie_comments",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">comment</i> Comments</a><a href="{{path("app_movie_ratings",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">star_half</i> Ratings</a>
                  </div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-icon" data-background-color="rose">
						<i class="material-icons">recent_actors</i>
					</div>
					<div class="card-content">
						<h4 class="card-title">{{movie.title}} Cast</h4>
					</div>
				</div>
				<div class="row">
					<div class="col-md-3">
						<div class="card card-profile card-initial">
							<div class="card-avatar">
								<a href="#">
									<img class="img" src="{{asset("img/add.png")|imagine_filter('actor_thumb')}}">
								</a>
							</div>
							<div class="card-content">
								{{form_start(role_form)}}
								<div class="form-group label-floating is-empty">
									{{form_widget(role_form.role,{"attr":{"class":"form-control form-control-role","placeholder":"Role"}})}}
									<span class="validate-input">{{form_errors(role_form.role)}}</span>
								</div>
								<div class="form-group label-floating is-empty">
									{{form_widget(role_form.actor,{"attr":{"class":"form-control form-control-role","placeholder":"Actor/Director"}})}}
									<span class="validate-input">{{form_errors(role_form.actor)}}</span>
								</div>
								<span>{{form_widget(role_form.save,{attr:{"class":"btn btn-success btn-xs form-control-role"}})}}</span>
								{{form_end(role_form)}}
							</div>
						</div>
					</div>
					<script type="text/javascript">
					$("#Role_actor").selectize();
					</script>
					{% for role in pagination %}
						<div class="col-md-3">
							<div class="card card-profile card-initial">
								<div class="card-avatar">
									<a href="#">
										<img class="img" src="{{asset(role.actor.media.link)|imagine_filter('actor_thumb')}}">
									</a>
								</div>
								<div class="card-content">
									<h5 class="card-title"><b>{{role.actor.name}}</b></h5>
									<h5 class="card-sub-title" style="color:gray"><b>{{role.role}}</b></h5>
									<a href="{{path("app_role_edit",{"id":role.id})}}" class="btn btn-success btn-xs"><i class="material-icons">edit</i></a>
									<a href="{{path("app_role_delete",{"id":role.id})}}" class="btn btn-rose btn-xs"><i class="material-icons">delete</i></a>
									<a href="{{path("app_role_up",{"id":role.id})}}" class="btn btn-info btn-xs"><i class="material-icons">keyboard_arrow_up</i></a>
									<a href="{{path("app_role_down",{"id":role.id})}}" class="btn btn-info btn-xs"><i class="material-icons">keyboard_arrow_down</i></a>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
									<div class=" pull-right">
						{{ knp_pagination_render(pagination) }}
					</div>
			</div>
		</div>
	</div>
{% endblock%}

src/AppBundle/Resources/views/Movie/comments.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card card-stats card-initial" style="margin: 15px 0;">
					<div class="card-content views-body  pull-right">
						<a href="#" class="btn btn-tab-movie"><i class="material-icons">remove_red_eye</i> {{movie.viewsnumber}} Views</a>
						<a href="#" class="btn btn-tab-movie pull-right"><i class="material-icons">share</i> {{movie.sharesnumber}} Shares</a>
						<a href="#" class="btn btn-tab-movie pull-right"><i class="material-icons">cloud_download</i> {{movie.downloadsnumber}} Downloads</a>
					</div>
					<div class="card-header " data-background-color="green">
						<i class="material-icons">movie_filter</i>
					</div>
					<div class="card-content trailer-body">
						<h4 class="title">Comments : {{movie.title }} </b></h4>
					</div>
                  <div class="tab-moivie">
                    <a href="{{path("app_movie_edit",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">edit</i> Edit</a><a href="{{path("app_movie_sources",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">folder</i> Sources</a><a href="{{path("app_movie_cast",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">recent_actors</i> Cast</a><a href="{{path("app_movie_trailer",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">movie_filter</i> Trailer</a><a href="{{path("app_movie_subtitles",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">subtitles</i> Subtitles</a><a href="{{path("app_movie_comments",{"id":movie.id})}}" class="btn btn-tab-movie-active"><i class="material-icons">comment</i> Comments</a><a href="{{path("app_movie_ratings",{"id":movie.id})}}" class="btn btn-tab-movie"><i class="material-icons">star_half</i> Ratings</a>
                  </div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="card">
					<div class="card-header card-header-icon" data-background-color="rose">
						<i class="material-icons">comment</i>
					</div>
					<div class="card-content">
						<h4 class="card-title">{{movie.title}}: {{count}} Comments </h4>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						{% for comment in pagination %}
							<div class="col-md-6">
								<ul class="timeline timeline-simple">
									<li class="timeline-inverted">
										<div class="timeline-badge info">
											{% if comment.user.media != null %}
												{% if comment.user.media.type =="link" %}
													<img class="avatar-char palette-Red-400 bg"  style="border-radius: 100px;    border: 0.5px solid #ccc;" src="{{comment.user.media.url}}" alt="">
												{% else %}
													<img class="avatar-char palette-Red-400 bg"  style="border-radius: 100px;    border: 0.5px solid #ccc;" src="{{asset(comment.user.media.link)|imagine_filter('actor_thumb')}}" alt="">
												{% endif %}
											{% else %}
												<img class="avatar-char palette-Red-400 bg"  style="border-radius: 100px;    border: 0.5px solid #ccc;" src="{{asset("img/avatar.jpg")|imagine_filter('actor_thumb')}}" alt="">
											{% endif %}
										</div>
										<div class="timeline-panel">
											<div class="timeline-heading">
												<a href="{{path("user_user_edit",{id:comment.user.id})}}" title="">
													<span class="label label-danger">{{comment.user.name}}</span>
												</a>
												<span class="pull-right" >
													<a href="{{path("app_comment_delete",{id:comment.id,"poster":"true"})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Delete">
														<i class="material-icons" style="color:red">delete</i>
													</a>
													{% if comment.enabled %}
														<a href="{{path("app_comment_hide",{id:comment.id})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Hide">
															<i class="material-icons">visibility_off</i>
														</a>
													{% else %}
														<a href="{{path("app_comment_hide",{id:comment.id})}}"  rel="tooltip" data-placement="bottom" title="" data-original-title="Show">
															<i class="material-icons">remove_red_eye</i>
														</a>
													{% endif %}
												</span>
											</div>
											<div class="timeline-body">
												<p>{{comment.contentclear}}</p>
											</div>
											<hr class="hr-10">
											<small class="pull-right label label-rose">
											<span>{{comment.created|ago}}</span>
											</small>
										</div>
									</li>
									
								</ul>
							</div>
						{% else %}
							<div class="card"  style="text-align: center;" >
								<br>
								<br>
								<img src="{{asset("img/bg_empty.png")}}"  style="width: auto !important;" ="">
								<br>
								<br>
							</div>
						{% endfor %}
					</div>
					<div class=" pull-right">
						{{ knp_pagination_render(pagination) }}
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock%}

src/AppBundle/Resources/views/Movie/delete.html.twig
{% extends "AppBundle::layout.html.twig" %}
{% block body%}
<div class="container-fluid">
	<div class="swal2-modal swal2-show" style="display: block; width: 500px; padding: 20px; background: rgb(255, 255, 255); min-height: 332px;" tabindex="-1">
	    <ul class="swal2-progresssteps" style="display: none;"></ul>
	    <div class="swal2-icon swal2-error" style="display: none;"><span class="x-mark"><span class="line left"></span><span class="line right"></span></span>
	    </div>
	    <div class="swal2-icon swal2-question" style="display: none;">?</div>
	    <div class="swal2-icon swal2-warning pulse-warning" style="display: block;">!</div>
	    <div class="swal2-icon swal2-info" style="display: none;">i</div>
	    <div class="swal2-icon swal2-success" style="display: none;"><span class="line tip"></span> <span class="line long"></span>
	        <div class="placeholder"></div>
	        <div class="fix"></div>
	    </div><img class="swal2-image" style="display: none;">
	    <h2>Are you sure</h2>
	    <div class="swal2-content" style="display: block;">Do you really want to delete this Movie</div>
	    <div class="swal2-content" style="display: block;color:red;font-size: 12pt;">All Sources and subtitles of this movie will be deleted too</div>
	    <input class="swal2-input" style="display: none;">
	    <input type="file" class="swal2-file" style="display: none;">
	    <div class="swal2-range" style="display: none;">
	        <output></output>
	        <input type="range">
	    </div>
	    <select class="swal2-select" style="display: none;"></select>
	    <div class="swal2-radio" style="display: none;"></div>
	    <label for="swal2-checkbox" class="swal2-checkbox" style="display: none;">
	        <input type="checkbox">
	    </label>
	    <textarea class="swal2-textarea" style="display: none;"></textarea>
	    <div class="swal2-validationerror" style="display: none;"></div>
	    <hr class="swal2-spacer" style="display: block;">
	    {{form_start(form)}}
              {{form_widget(form.Yes,{"attr":{"class":"swal2-confirm btn btn-success"}})}}
              <a href="{{path("app_movie_index")}}" class="swal2-cancel btn btn-danger">Cancel</a>
		{{form_end(form)}}
	</div>
</div>
{% endblock%}